import type { AppointmentEntry, BaseAppointmentDetails, ConsultationDetails } from "@/types/appointment";

// Mock data para atendimentos.
// Em uma aplicação real, isso viria de um serviço/DB.
export const mockAppointments: AppointmentEntry[] = [
  {
    id: "app1",
    animalId: "a1",
    date: "2023-10-26",
    time: "10:00",
    type: "Consulta",
    vet: "Dr. William Cardoso",
    pesoAtual: 25.0,
    temperaturaCorporal: 38.5,
    observacoesGerais: "Animal saudável, check-up de rotina.",
    details: {
      queixaPrincipal: "Check-up anual",
      historicoClinico: "Sem intercorrências recentes.",
      alimentacao: "Ração seca premium",
      vacinacaoVermifugacaoAtualizadas: "sim",
      ambiente: "interno",
      contatoOutrosAnimais: "nao",
      mucosas: "róseas, úmidas",
      frequenciaCardiaca: 100,
      frequenciaRespiratoria: 20,
      diagnosticoDefinitivo: "Saudável",
      condutaTratamento: "Manter rotina, próxima vacina em 6 meses.",
      retornoRecomendadoEmDias: 180,
    } as ConsultationDetails,
    attachments: [],
  },
  {
    id: "app2",
    animalId: "a1",
    date: "2024-03-10",
    time: "11:30",
    type: "Vacina",
    vet: "Dra. Ana Paula",
    pesoAtual: 25.5,
    temperaturaCorporal: 38.0,
    observacoesGerais: "Aplicação da vacina V8.",
    details: {
      tipoVacina: "V8",
      dose: "1ª dose",
      nomeComercial: "Duramune Max 5/4L",
      lote: "ABC123XYZ",
      fabricante: "Boehringer Ingelheim",
      dataFabricacao: "2023-01-01",
      dataValidade: "2025-01-01",
      doseAplicada: 1.0,
      viaAdministracao: "SC",
      localAplicacao: "Escapular direita",
      reacaoAdversaObservada: "Nenhuma",
      profissionalAplicou: "Dra. Ana Paula",
      proximaDose: "2024-04-10",
    },
    attachments: [],
  },
  {
    id: "app3",
    animalId: "a3",
    date: "2024-01-15",
    time: "14:30",
    type: "Emergência",
    vet: "Dr. Carlos Eduardo",
    pesoAtual: 18.0,
    temperaturaCorporal: 39.5,
    observacoesGerais: "Animal chegou com dispneia e tosse.",
    details: {
      horaChegada: "14:30",
      condicaoGeral: "dispneia",
      manobrasSuporteRealizadas: "Oxigenoterapia, fluidoterapia.",
      medicamentosAdministrados: "Furosemida, Dexametasona.",
      encaminhamento: "internacao",
    } as BaseAppointmentDetails,
    attachments: [],
  },
  {
    id: "app4",
    animalId: "a1",
    date: "2024-07-25",
    time: "15:00",
    type: "Outros",
    vet: "Dr. William Cardoso",
    pesoAtual: 26.0,
    temperaturaCorporal: 38.2,
    observacoesGerais: "Animal com leve tosse. Prescrito xarope.",
    details: {
      queixaPrincipal: "Tosse leve",
      condutaTratamento: "Xarope para tosse por 5 dias.",
    } as BaseAppointmentDetails,
    attachments: [],
  },
];