// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wlkowsdfkfwyyypnqvis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsa293c2Rma2Z3eXl5cG5xdmlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0OTQ1MjEsImV4cCI6MjA4MTA3MDUyMX0.20yueeumnSs4oFfRqHDGdP8_9wAJrYo0aDCSRJwzKWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);